/* =====================================================================
   PANDA'VENTURE × WWF — data.js
   Types de questions : mcq | tf | estimate | order
   ===================================================================== */

const STOPS = [
  /* ── 1 · Musée du Louvre · Tortue terrestre ─────────────────────── */
  {
    id: 1,
    monument:  "Musée du Louvre",
    species:   "Tortue terrestre",
    photo:     "charte graphique panda'venture/Photos WWF/Original_WW211131.jpg",
    monumentPhoto:      "https://images.unsplash.com/photo-1564557823522-1319c627a1e3?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Tortue terrestre.png",
    color:      "#5CB87A",
    colorLight: "#D8F3DC",
    colorDark:  "#1A5C35",
    slogan:     "La sagesse\nà travers les siècles",
    emoji:      "🐢",
    panelCoords:[48.8606, 2.3376],
    fact:       "Certaines tortues terrestres vivent plus de 150 ans. Elles ont survécu aux dinosaures — mais pas encore à l'Homme.",
    wwfAction:  "WWF protège les corridors migratoires des tortues et lutte contre le trafic illégal d'espèces dans le monde entier.",
    quiz: [
      { type:'mcq', q:"Quelle est la durée de vie maximale connue d'une tortue terrestre ?", answers:["Plus de 150 ans","Environ 50 ans","30 ans","Plus de 300 ans"], correct:0, points:10 },
      { type:'mcq', q:"Depuis combien de millions d'années les tortues existent-elles sur Terre ?", answers:["220 millions d'années","65 millions d'années","10 millions d'années","500 millions d'années"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la principale menace pour les tortues terrestres ?", answers:["Trafic d'espèces et perte d'habitat","Les prédateurs naturels","La pollution de l'air","Le bruit"], correct:0, points:10 },
      { type:'tf',  q:"Les tortues n'ont pas de dents — elles possèdent un bec corné.", correct:true, points:5 },
      { type:'tf',  q:"Les tortues sont des mammifères.", correct:false, points:5 },
      { type:'tf',  q:"Les tortues marines reviennent toujours pondre sur la plage où elles sont nées.", correct:true, points:5 },
      { type:'tf',  q:"La tortue géante des Galapagos est déjà éteinte.", correct:false, points:5 },
      { type:'tf',  q:"Une tortue peut sortir de sa carapace, qui n'est pas une coquille mais fait partie de son squelette.", correct:false, points:5 },
      { type:'estimate', q:"Combien d'espèces de tortues existent dans le monde ?", min:50, max:600, answer:360, unit:"espèces", points:15 },
      { type:'estimate', q:"Quel poids peut atteindre une tortue géante des Galapagos adulte (en kg) ?", min:50, max:500, answer:250, unit:"kg", points:15 },
      { type:'mcq', q:"De quoi se nourrit principalement une tortue terrestre ?", answers:["Végétaux et fruits","Poissons","Insectes","Petits mammifères"], correct:0, points:10 },
      { type:'mcq', q:"Qu'est-ce que la convention CITES ?", answers:["Un traité réglementant le commerce des espèces sauvages","Un accord sur la réduction du CO₂","Une organisation humanitaire de l'ONU","Un traité de protection des océans"], correct:0, points:10 },
      { type:'mcq', q:"Comment s'appelle la partie inférieure de la carapace d'une tortue ?", answers:["Le plastron","L'écusson","Le bouclier","La plaque ventrale"], correct:0, points:10 },
      { type:'mcq', q:"Où trouve-t-on la tortue géante des Galapagos ?", answers:["Îles Galapagos (Équateur)","Archipel des Maldives","Australie","Japon"], correct:0, points:10 },
      { type:'mcq', q:"Pourquoi le WWF a-t-il choisi le panda comme logo ?", answers:["Espèce menacée et charismatique réduisant aussi les coûts d'impression (logo noir & blanc)","Il était commun dans le monde entier","Il est le plus fort des animaux","Il symbolise la paix universelle"], correct:0, points:10 },
      { type:'tf',  q:"Certaines tortues peuvent survivre plus d'un an sans manger.", correct:true, points:5 },
      { type:'order', q:"Classez ces animaux du plus ANCIEN (premier apparu sur Terre) au plus récent.", items:["Humain","Méduse","Crocodile","Tortue"], correct:["Méduse","Tortue","Crocodile","Humain"], points:15 },
      { type:'estimate', q:"Combien de temps (en heures) une tortue marine peut-elle retenir sa respiration sous l'eau ?", min:1, max:20, answer:7, unit:"heures", points:15 },
      { type:'mcq', q:"Le WWF a été fondé en quelle année ?", answers:["1961","1945","1972","1980"], correct:0, points:10 },
      { type:'mcq', q:"Qu'est-ce que la thermorégulation comportementale ?", answers:["Réguler sa température en changeant d'endroit (ombre/soleil)","Produire de la chaleur par des frissons","Transpirer pour se refroidir","Hiberner tout l'hiver"], correct:0, points:10 },
    ]
  },

  /* ── 2 · Notre-Dame de Paris · Coraux ───────────────────────────── */
  {
    id: 2,
    monument:  "Notre-Dame de Paris",
    species:   "Coraux",
    photo:     "charte graphique panda'venture/Photos WWF/Original_WW210836.jpg",
    monumentPhoto:      "https://images.unsplash.com/photo-1548092492-79f224d33b2f?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Coraux.png",
    color:      "#C45A10",
    colorLight: "#FEF0E7",
    colorDark:  "#7F3200",
    slogan:     "Quand la fragilité\ndevient trésor",
    emoji:      "🪸",
    panelCoords:[48.8530, 2.3499],
    fact:       "Les récifs coralliens couvrent moins de 1% des océans mais abritent 25% de toutes les espèces marines.",
    wwfAction:  "WWF travaille à la réduction des émissions de CO₂ et au développement de programmes de restauration corallienne à l'échelle mondiale.",
    quiz: [
      { type:'mcq', q:"Quel pourcentage des espèces marines vit dans les récifs coralliens ?", answers:["25%","5%","50%","10%"], correct:0, points:10 },
      { type:'mcq', q:"De combien de degrés la température doit-elle monter pour provoquer le blanchissement des coraux ?", answers:["+1°C au-dessus de la normale","+5°C","+0,1°C","+10°C"], correct:0, points:10 },
      { type:'mcq', q:"Quelle proportion des récifs coralliens est déjà dégradée ?", answers:["Environ la moitié","10%","90%","Moins de 5%"], correct:0, points:10 },
      { type:'tf',  q:"Le corail est un animal, et non une plante.", correct:true, points:5 },
      { type:'tf',  q:"Le blanchissement des coraux signifie leur mort immédiate et définitive.", correct:false, points:5 },
      { type:'tf',  q:"Les récifs coralliens couvrent plus de 10% des fonds marins.", correct:false, points:5 },
      { type:'tf',  q:"L'acidification des océans causée par le CO₂ menace directement les coraux.", correct:true, points:5 },
      { type:'tf',  q:"Il existe des récifs coralliens dans des eaux froides et profondes.", correct:true, points:5 },
      { type:'estimate', q:"Combien d'années faut-il à un récif corallien pour se reconstituer après un blanchissement sévère ?", min:1, max:50, answer:10, unit:"années", points:15 },
      { type:'estimate', q:"En quelle année la Grande Barrière de corail a-t-elle été inscrite au patrimoine mondial de l'UNESCO ?", min:1970, max:2000, answer:1981, unit:"", points:15 },
      { type:'mcq', q:"Qu'est-ce que le blanchissement des coraux ?", answers:["L'expulsion des algues symbiotiques qui leur donnent couleur et nourriture","Une floraison naturelle saisonnière","La mort directe du corail","Une réaction au sel"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la plus grande structure vivante sur Terre ?", answers:["La Grande Barrière de corail (Australie)","La forêt amazonienne","Le réseau de champignons Armillaria","Les prairies des Grandes Plaines"], correct:0, points:10 },
      { type:'mcq', q:"Quel pourcentage des récifs pourrait disparaître si la température monte de +2°C ?", answers:["90%","20%","50%","5%"], correct:0, points:10 },
      { type:'mcq', q:"Combien d'espèces de poissons vivent dans les récifs coralliens ?", answers:["Environ 4 000","Environ 100","Plus de 50 000","Environ 500"], correct:0, points:10 },
      { type:'mcq', q:"Qu'ont en commun Notre-Dame et les récifs coralliens ?", answers:["Tous deux sont des trésors fragiles que l'Homme a failli perdre — et qu'il tente de restaurer","Tous deux sont sous l'eau","Tous deux datent du Moyen Âge","Tous deux se trouvent en France"], correct:0, points:10 },
      { type:'tf',  q:"Notre-Dame de Paris a été restaurée grâce à des dons dépassant 800 millions d'euros.", correct:true, points:5 },
      { type:'order', q:"Classez ces mers de la plus CHAUDE à la plus froide en surface.", items:["Mer de Norvège","Mer Rouge","Mer Méditerranée","Mer des Caraïbes"], correct:["Mer Rouge","Mer des Caraïbes","Mer Méditerranée","Mer de Norvège"], points:15 },
      { type:'estimate', q:"À quelle profondeur (en mètres) vivent la plupart des récifs coralliens tropicaux ?", min:0, max:100, answer:30, unit:"m", points:15 },
      { type:'mcq', q:"Que fait concrètement le WWF pour restaurer les coraux ?", answers:["Programmes de replantation de coraux et réduction des émissions mondiales","Interdire toute plongée","Construire des récifs artificiels en plastique","Transplanter les coraux en aquariums"], correct:0, points:10 },
      { type:'mcq', q:"Quel gaz est principalement responsable de l'acidification des océans ?", answers:["CO₂","CH₄ (méthane)","N₂O (protoxyde d'azote)","SO₂ (dioxyde de soufre)"], correct:0, points:10 },
    ]
  },

  /* ── 3 · Arc de Triomphe · Éléphant ─────────────────────────────── */
  {
    id: 3,
    monument:  "Arc de Triomphe",
    species:   "Éléphant",
    photo:     "charte graphique panda'venture/Photos WWF/wwf-photography-img_8.webp",
    monumentPhoto:      "https://images.unsplash.com/photo-1564687881345-8bb27894bc28?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Éléphant.png",
    color:      "#5BA3D9",
    colorLight: "#DBEAFE",
    colorDark:  "#1A4A7A",
    slogan:     "Les gardiens\nde l'histoire",
    emoji:      "🐘",
    panelCoords:[48.8738, 2.2950],
    fact:       "Les éléphants plantent des arbres, creusent des puits et créent des chemins — ils façonnent les écosystèmes entiers.",
    wwfAction:  "WWF lutte contre le braconnage pour l'ivoire et protège les corridors migratoires des éléphants en Afrique et en Asie.",
    quiz: [
      { type:'mcq', q:"Comment les éléphants contribuent-ils à la reforestation ?", answers:["En dispersant des graines dans leurs déjections","En creusant le sol","En arrosant les plantes avec leur trompe","En protégeant les arbres des prédateurs"], correct:0, points:10 },
      { type:'mcq', q:"Combien d'éléphants sont tués chaque année pour leur ivoire ?", answers:["Environ 20 000","Environ 100","Plus de 100 000","Environ 5 000"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la durée de gestation d'une éléphante ?", answers:["22 mois","6 mois","12 mois","36 mois"], correct:0, points:10 },
      { type:'tf',  q:"L'éléphant est le plus grand animal terrestre.", correct:true, points:5 },
      { type:'tf',  q:"Un éléphant peut se reconnaître dans un miroir, preuve d'une conscience de soi.", correct:true, points:5 },
      { type:'tf',  q:"L'éléphant d'Afrique et l'éléphant d'Asie appartiennent à la même espèce.", correct:false, points:5 },
      { type:'tf',  q:"La trompe d'un éléphant contient plus de 100 000 muscles.", correct:true, points:5 },
      { type:'tf',  q:"L'éléphant est le seul mammifère incapable de sauter.", correct:true, points:5 },
      { type:'estimate', q:"Combien de litres d'eau un éléphant adulte boit-il par jour ?", min:10, max:400, answer:180, unit:"litres", points:15 },
      { type:'estimate', q:"Quel est le poids moyen d'un éléphant d'Afrique adulte mâle (en kg) ?", min:1000, max:10000, answer:6000, unit:"kg", points:15 },
      { type:'mcq', q:"Combien reste-t-il d'éléphants de savane d'Afrique ?", answers:["Environ 415 000","Plus de 1 million","Environ 50 000","Plus de 2 millions"], correct:0, points:10 },
      { type:'mcq', q:"Comment les éléphants communiquent-ils sur de longues distances ?", answers:["Par des infrasons (sons trop graves pour l'oreille humaine)","Par des cris ultrasoniques","Par des signaux visuels","Par des phéromones"], correct:0, points:10 },
      { type:'mcq', q:"Quel pays accueille la plus grande population d'éléphants sauvages d'Afrique ?", answers:["Botswana","Kenya","Tanzanie","Zimbabwe"], correct:0, points:10 },
      { type:'mcq', q:"Que signifie le mot 'braconnage' ?", answers:["La chasse ou la pêche illégale d'espèces sauvages","La pêche intensive","La déforestation","L'agriculture sur brûlis"], correct:0, points:10 },
      { type:'mcq', q:"Pourquoi l'ivoire est-il si recherché ?", answers:["Pour la sculpture et les objets d'art, ainsi que la médecine traditionnelle en Asie","Uniquement comme matériau de construction","Comme source d'alimentation","Pour fabriquer des instruments de musique"], correct:0, points:10 },
      { type:'tf',  q:"Les éléphants sont connus pour pleurer la mort de leurs congénères.", correct:true, points:5 },
      { type:'order', q:"Classez ces animaux du PLUS LOURD au plus léger.", items:["Girafe","Éléphant d'Afrique","Rhinocéros blanc","Hippopotame"], correct:["Éléphant d'Afrique","Hippopotame","Rhinocéros blanc","Girafe"], points:15 },
      { type:'estimate', q:"Combien de fois dans sa vie un éléphant renouvelle-t-il ses molaires ?", min:1, max:15, answer:6, unit:"fois", points:15 },
      { type:'mcq', q:"Qu'est-ce qu'un 'couloir migratoire' ?", answers:["Une zone naturelle permettant aux animaux de se déplacer entre habitats","Un canal artificiel","Une zone protégée fermée au public","Un sentier touristique balisé"], correct:0, points:10 },
      { type:'mcq', q:"Quelle organisation internationale réglemente le commerce de l'ivoire ?", answers:["La CITES","L'UNESCO","La FAO","Greenpeace"], correct:0, points:10 },
    ]
  },

  /* ── 4 · Hôtel des Invalides · Cactus ───────────────────────────── */
  {
    id: 4,
    monument:  "Hôtel des Invalides",
    species:   "Cactus",
    photo:     "charte graphique panda'venture/Photos WWF/Original_WW245406.jpg",
    monumentPhoto:      "https://images.unsplash.com/photo-1545251804-7e27e8d79aaa?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Cactus.png",
    color:      "#2D6A4F",
    colorLight: "#E0F2EF",
    colorDark:  "#0A3D28",
    slogan:     "La robustesse\nincarnée",
    emoji:      "🌵",
    panelCoords:[48.8535, 2.3122],
    fact:       "Les cactus peuvent stocker des centaines de litres d'eau. Mais ils disparaissent à cause du trafic de plantes sauvages.",
    wwfAction:  "WWF milite pour l'application de la convention CITES qui réglemente le commerce international des cactus sauvages.",
    quiz: [
      { type:'mcq', q:"Quelle convention internationale protège le commerce des cactus sauvages ?", answers:["La CITES","Le protocole de Kyoto","L'accord de Paris","La convention de Berne"], correct:0, points:10 },
      { type:'mcq', q:"Combien de litres d'eau un grand cactus saguaro peut-il stocker ?", answers:["Des centaines de litres","Quelques décilitres","Exactement 1 litre","Des milliers de litres"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la principale menace pesant sur les cactus dans le monde ?", answers:["Le trafic de plantes sauvages","La sécheresse excessive","Les parasites","La pollution de l'air"], correct:0, points:10 },
      { type:'tf',  q:"Les cactus produisent des fleurs, souvent très colorées.", correct:true, points:5 },
      { type:'tf',  q:"Tous les cactus sont originaires des Amériques.", correct:true, points:5 },
      { type:'tf',  q:"Les épines des cactus sont en réalité des feuilles très transformées.", correct:true, points:5 },
      { type:'tf',  q:"Les cactus ouvrent leurs pores (stomates) le jour pour absorber le CO₂.", correct:false, points:5 },
      { type:'tf',  q:"Le cactus de Noël (Schlumbergera) pousse naturellement dans les déserts.", correct:false, points:5 },
      { type:'estimate', q:"Combien d'espèces de cactus existent dans le monde ?", min:100, max:5000, answer:2000, unit:"espèces", points:15 },
      { type:'estimate', q:"Quel pourcentage de la surface terrestre est couvert par des déserts ?", min:5, max:60, answer:33, unit:"%", points:15 },
      { type:'mcq', q:"Comment les cactus économisent-ils l'eau ?", answers:["Ils ferment leurs stomates le jour et les ouvrent la nuit","Ils ont des feuilles larges pour capter la rosée","Ils absorbent l'humidité par leur tige","Ils s'enfoncent dans le sol lors des canicules"], correct:0, points:10 },
      { type:'mcq', q:"Qu'est-ce que la 'désertification' ?", answers:["L'extension des zones arides due aux activités humaines et au changement climatique","La plantation d'arbres en zone désertique","L'irrigation artificielle des déserts","La protection des oasis"], correct:0, points:10 },
      { type:'mcq', q:"Le grand cactus saguaro pousse principalement dans quel État américain ?", answers:["L'Arizona","La Californie","Le Texas","Le Nevada"], correct:0, points:10 },
      { type:'mcq', q:"Qu'est-ce que la 'succulence' ?", answers:["La capacité à stocker de l'eau dans les tissus charnues","Une saveur sucrée caractéristique","Un type de sol particulier","Un mode de reproduction végétal"], correct:0, points:10 },
      { type:'mcq', q:"Pourquoi est-il illégal de déplanter certains cactus aux États-Unis ?", answers:["Ce sont des espèces protégées par la loi fédérale","Ils sont dangereux à transporter","Ils appartiennent à l'État","Ils sont sacrés pour les Amérindiens"], correct:0, points:10 },
      { type:'tf',  q:"Certains cactus peuvent vivre plus de 200 ans.", correct:true, points:5 },
      { type:'order', q:"Classez ces zones climatiques de la plus ARIDE à la plus humide.", items:["Forêt tropicale","Savane","Désert","Steppe"], correct:["Désert","Steppe","Savane","Forêt tropicale"], points:15 },
      { type:'estimate', q:"À quelle température extrême certains cactus peuvent-ils résister (en °C) ?", min:40, max:80, answer:70, unit:"°C", points:15 },
      { type:'mcq', q:"Quel est le principal rôle écologique du cactus dans son milieu ?", answers:["Nourrir et abriter de nombreux animaux du désert","Purifier l'eau","Fixer l'azote dans le sol","Refroidir l'air ambiant"], correct:0, points:10 },
      { type:'mcq', q:"Quel continent est le plus touché par la désertification ?", answers:["L'Afrique","L'Asie","L'Amérique du Sud","L'Australie"], correct:0, points:10 },
    ]
  },

  /* ── 5 · Musée des Arts Décoratifs · Léopard de l'Amour ─────────── */
  {
    id: 5,
    monument:  "Musée des Arts Décoratifs",
    species:   "Léopard de l'Amour",
    photo:     "charte graphique panda'venture/Photos WWF/Original_WW210932.jpg",
    monumentPhoto:      "https://images.unsplash.com/photo-1552585734-b7ae2174b8f9?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Léopard de l'Amour.png",
    color:      "#7A4F2D",
    colorLight: "#F3E5DC",
    colorDark:  "#3E2010",
    slogan:     "La beauté sauvage\nà l'état pur",
    emoji:      "🐆",
    panelCoords:[48.8637, 2.3392],
    fact:       "Il reste moins de 100 léopards de l'Amour à l'état sauvage. C'est l'un des félins les plus rares au monde.",
    wwfAction:  "WWF coopère avec les gouvernements russe et chinois pour étendre et protéger l'habitat du léopard de l'Amour.",
    quiz: [
      { type:'mcq', q:"Combien de léopards de l'Amour restent-ils à l'état sauvage ?", answers:["Moins de 100","Environ 1 000","Plus de 5 000","Environ 500"], correct:0, points:10 },
      { type:'mcq', q:"Dans quelle région le léopard de l'Amour vit-il ?", answers:["Extrême-Orient russe et nord-est de la Chine","Afrique subsaharienne","Inde","Amazonie"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la vitesse maximale du léopard ?", answers:["58 km/h","100 km/h","30 km/h","80 km/h"], correct:0, points:10 },
      { type:'tf',  q:"Le léopard et la panthère sont deux noms pour le même animal.", correct:true, points:5 },
      { type:'tf',  q:"Le léopard de l'Amour peut grimper aux arbres pour mettre ses proies à l'abri.", correct:true, points:5 },
      { type:'tf',  q:"Les taches du léopard s'appellent des 'marbrures'.", correct:false, points:5 },
      { type:'tf',  q:"Le léopard de l'Amour est principalement actif la nuit (nocturne).", correct:true, points:5 },
      { type:'tf',  q:"Le léopard est un excellent nageur.", correct:true, points:5 },
      { type:'estimate', q:"Quelle est la superficie approximative du territoire d'un léopard de l'Amour mâle (en km²) ?", min:10, max:1000, answer:300, unit:"km²", points:15 },
      { type:'estimate', q:"En quelle année le léopard de l'Amour a-t-il été classé 'en danger critique' par l'UICN ?", min:1990, max:2010, answer:1996, unit:"", points:15 },
      { type:'mcq', q:"Pourquoi le léopard de l'Amour résiste-t-il mieux au froid que les autres léopards ?", answers:["Sa fourrure est plus épaisse et plus longue en hiver","Il hiberne plusieurs mois","Il migre vers le sud","Il produit plus de chaleur corporelle"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la principale cause de la raréfaction du léopard de l'Amour ?", answers:["Destruction de son habitat combinée au braconnage","Maladies virales","Manque de proies naturelles","Compétition avec d'autres félins"], correct:0, points:10 },
      { type:'mcq', q:"Qu'est-ce qu'une espèce 'en danger critique d'extinction' (CR) selon l'UICN ?", answers:["Le niveau de menace le plus élevé avant l'extinction totale","Une espèce simplement malade","Une espèce protégée par la loi","Une espèce invasive"], correct:0, points:10 },
      { type:'mcq', q:"Combien d'espèces de félins sauvages existe-t-il dans le monde ?", answers:["Environ 40","Environ 10","Environ 100","Environ 20"], correct:0, points:10 },
      { type:'mcq', q:"Quel grand félin partage le même territoire russe que le léopard de l'Amour ?", answers:["Le tigre de l'Amour (Sibérie)","Le lion","Le guépard","Le puma"], correct:0, points:10 },
      { type:'tf',  q:"Le mouvement Art Nouveau, présent aux Arts Décoratifs, s'inspire des formes animales et végétales.", correct:true, points:5 },
      { type:'order', q:"Classez ces félins du PLUS NOMBREUX au plus rare dans la nature.", items:["Léopard de l'Amour","Guépard","Lion d'Afrique","Tigre de Sibérie"], correct:["Lion d'Afrique","Guépard","Tigre de Sibérie","Léopard de l'Amour"], points:15 },
      { type:'order', q:"Classez ces félins du plus PETIT au plus grand (poids).", items:["Tigre de Sibérie","Guépard","Jaguar","Léopard de l'Amour"], correct:["Guépard","Léopard de l'Amour","Jaguar","Tigre de Sibérie"], points:15 },
      { type:'mcq', q:"Que signifie 'biodiversité' ?", answers:["La variété de toutes les formes de vie sur Terre","Le nombre total d'espèces marines","La biomasse totale des forêts","La diversité génétique d'une seule espèce"], correct:0, points:10 },
      { type:'mcq', q:"Comment WWF aide-t-il le léopard de l'Amour ?", answers:["En agrandissant les zones protégées et en coopérant avec la Russie et la Chine","En les élevant en captivité uniquement","En les nourrissant directement","En interdisant tout tourisme dans la région"], correct:0, points:10 },
    ]
  },

  /* ── 6 · Musée de l'Orangerie · Acajou à grandes feuilles ──────── */
  {
    id: 6,
    monument:  "Musée de l'Orangerie",
    species:   "Acajou à grandes feuilles",
    photo:     "charte graphique panda'venture/Photos WWF/Original_WW1110229.jpg",
    monumentPhoto:      "https://images.unsplash.com/photo-1657202242921-7fe1754fb77e?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Acajou.png",
    color:      "#A02818",
    colorLight: "#FDEDEC",
    colorDark:  "#6A1010",
    slogan:     "La force enracinée\nau cœur de l'histoire",
    emoji:      "🌳",
    panelCoords:[48.8638, 2.3218],
    fact:       "L'acajou à grandes feuilles est en danger d'extinction. Il faut 60 ans pour qu'il atteigne sa pleine maturité.",
    wwfAction:  "WWF lutte contre l'exploitation forestière illégale et promeut la certification durable du bois à l'international.",
    quiz: [
      { type:'mcq', q:"Combien d'années faut-il à un acajou à grandes feuilles pour atteindre sa taille adulte ?", answers:["60 ans","10 ans","200 ans","5 ans"], correct:0, points:10 },
      { type:'mcq', q:"Sur quelle liste de conservation l'acajou à grandes feuilles est-il classé ?", answers:["Liste rouge de l'UICN (Vulnerable)","Liste bleue de l'ONU","Liste verte de l'UNESCO","Il n'est sur aucune liste"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la principale menace pour l'acajou ?", answers:["L'exploitation forestière illégale","La pollution atmosphérique","Les parasites fongiques","Le gel hivernal"], correct:0, points:10 },
      { type:'tf',  q:"L'acajou est un bois précieux historiquement utilisé en ébénisterie de luxe.", correct:true, points:5 },
      { type:'tf',  q:"L'acajou à grandes feuilles pousse uniquement en Afrique.", correct:false, points:5 },
      { type:'tf',  q:"Le label FSC garantit que le bois provient d'une forêt gérée durablement.", correct:true, points:5 },
      { type:'tf',  q:"Une forêt tropicale détruite peut se reconstituer en 10 ans.", correct:false, points:5 },
      { type:'tf',  q:"La déforestation est l'une des principales causes de perte de biodiversité mondiale.", correct:true, points:5 },
      { type:'estimate', q:"Quel pourcentage des espèces terrestres vit dans les forêts tropicales ?", min:10, max:90, answer:50, unit:"%", points:15 },
      { type:'estimate', q:"Quel est l'âge de l'arbre le plus vieux du monde (en années) ?", min:500, max:10000, answer:5000, unit:"ans", points:15 },
      { type:'mcq', q:"Qu'est-ce que la 'déforestation' ?", answers:["La destruction des forêts pour l'agriculture, l'élevage ou l'urbanisation","La plantation d'arbres en zone urbaine","La gestion durable des forêts","Le reboisement après incendie"], correct:0, points:10 },
      { type:'mcq', q:"Environ combien d'espèces animales disparaissent chaque jour à cause de la déforestation ?", answers:["Environ 150","Environ 1","Plus de 1 000","Environ 10"], correct:0, points:10 },
      { type:'mcq', q:"Quel peintre, dont les Nymphéas ornent ce musée, était passionné par son jardin naturel ?", answers:["Claude Monet","Pablo Picasso","Henri Matisse","Paul Cézanne"], correct:0, points:10 },
      { type:'mcq', q:"Que signifie la classification CITES Annexe II pour l'acajou ?", answers:["Son commerce international est réglementé et surveillé","Il est totalement interdit de commerce","Il bénéficie d'une protection locale uniquement","C'est un simple label de qualité"], correct:0, points:10 },
      { type:'mcq', q:"Quel continent possède la plus grande superficie de forêts tropicales ?", answers:["L'Amérique du Sud","L'Afrique","L'Asie du Sud-Est","L'Océanie"], correct:0, points:10 },
      { type:'tf',  q:"Les arbres tropicaux absorbent davantage de CO₂ que les arbres tempérés.", correct:true, points:5 },
      { type:'order', q:"Classez ces forêts tropicales par SUPERFICIE décroissante.", items:["Bornéo","Congo","Amazonie","Nouvelle-Guinée"], correct:["Amazonie","Congo","Bornéo","Nouvelle-Guinée"], points:15 },
      { type:'estimate', q:"Combien de millions d'hectares de forêts tropicales sont détruits chaque année ?", min:0.5, max:20, answer:5, unit:"millions d'ha", points:15 },
      { type:'mcq', q:"Que signifie 'biodiversité' ?", answers:["La variété de toutes les formes de vie sur Terre et leurs interactions","Le nombre d'espèces d'une seule forêt","La biomasse totale de la planète","La diversité des paysages naturels"], correct:0, points:10 },
      { type:'mcq', q:"Comment WWF lutte-t-il contre la déforestation illégale ?", answers:["Surveillance satellite, coopération avec les gouvernements et certification durable","En plantant des arbres uniquement","En organisant des manifestations","En interdisant tout commerce de bois"], correct:0, points:10 },
    ]
  },

  /* ── 7 · Musée d'Orsay · Loutre géante ─────────────────────────── */
  {
    id: 7,
    monument:  "Musée d'Orsay",
    species:   "Loutre géante",
    photo:     "charte graphique panda'venture/Photos WWF/Original_WW210919.jpg",
    monumentPhoto:      "https://images.unsplash.com/photo-1573301626856-8552b3889342?auto=format&fit=crop&w=900&q=80",
    speciesIllustration:"charte graphique panda'venture/Loutre géante.png",
    color:      "#F5C518",
    colorLight: "#FEF9C3",
    colorDark:  "#7A6000",
    slogan:     "L'élégance\nentre deux rives",
    emoji:      "🦦",
    panelCoords:[48.8600, 2.3266],
    fact:       "La loutre géante peut mesurer 1,80 m. Il en reste moins de 5 000 dans les forêts amazoniennes.",
    wwfAction:  "WWF préserve les zones humides amazoniennes, habitat vital de la loutre géante menacée par la déforestation.",
    quiz: [
      { type:'mcq', q:"Dans quelle région la loutre géante vit-elle principalement ?", answers:["Amazonie (Amérique du Sud)","Sibérie","Afrique centrale","Australie"], correct:0, points:10 },
      { type:'mcq', q:"Combien reste-t-il de loutres géantes à l'état sauvage ?", answers:["Moins de 5 000","Environ 50 000","Plus de 100 000","Environ 1 000"], correct:0, points:10 },
      { type:'mcq', q:"Quelle est la principale menace pour la loutre géante ?", answers:["La destruction des zones humides amazoniennes","La sécheresse","Les grands félins","La pollution lumineuse"], correct:0, points:10 },
      { type:'tf',  q:"La loutre géante peut mesurer jusqu'à 1,80 mètre de long.", correct:true, points:5 },
      { type:'tf',  q:"La loutre est un oiseau aquatique.", correct:false, points:5 },
      { type:'tf',  q:"Les loutres (de mer) utilisent des outils pour ouvrir des coquillages.", correct:true, points:5 },
      { type:'tf',  q:"La loutre géante vit en groupe familial et élève ses petits collectivement.", correct:true, points:5 },
      { type:'tf',  q:"Les zones humides couvrent plus de 20% de la surface terrestre.", correct:false, points:5 },
      { type:'estimate', q:"Quel pourcentage des zones humides mondiales a disparu depuis 1900 ?", min:5, max:80, answer:35, unit:"%", points:15 },
      { type:'estimate', q:"Combien de kg de poissons une loutre géante mange-t-elle par jour ?", min:0.5, max:15, answer:3.5, unit:"kg", points:15 },
      { type:'mcq', q:"Qu'est-ce qu'une 'zone humide' ?", answers:["Un milieu naturel saturé d'eau (marais, tourbière, mangrove, delta…)","La mer ouverte","Une forêt tropicale","Une prairie sèche"], correct:0, points:10 },
      { type:'mcq', q:"Quel service essentiel rendent les zones humides pour l'Homme ?", answers:["Filtration naturelle de l'eau et protection contre les inondations","Production de pétrole","Stockage de déchets industriels","Agriculture intensive"], correct:0, points:10 },
      { type:'mcq', q:"Le Musée d'Orsay est une ancienne…", answers:["Gare ferroviaire","Usine sidérurgique","Prison","Banque nationale"], correct:0, points:10 },
      { type:'mcq', q:"Combien d'espèces de loutres existent dans le monde ?", answers:["13 espèces","3 espèces","25 espèces","50 espèces"], correct:0, points:10 },
      { type:'mcq', q:"Qu'est-ce que la 'bioaccumulation' qui menace la loutre ?", answers:["La concentration de polluants qui augmente à chaque maillon de la chaîne alimentaire","La production de biomasse végétale","L'accumulation de carbone dans les sols","Le dépôt de sédiments dans les rivières"], correct:0, points:10 },
      { type:'tf',  q:"Les loutres géantes sont territoriales et défendent activement leur territoire.", correct:true, points:5 },
      { type:'order', q:"Classez ces fleuves du plus LONG au plus court.", items:["Yangtsé","Nil","Mississippi","Amazone"], correct:["Nil","Amazone","Yangtsé","Mississippi"], points:15 },
      { type:'order', q:"Classez ces mammifères aquatiques du plus GRAND au plus petit.", items:["Castor","Dugong","Loutre géante","Baleine bleue"], correct:["Baleine bleue","Dugong","Loutre géante","Castor"], points:15 },
      { type:'estimate', q:"Combien d'espèces de poissons vivent dans le bassin amazonien ?", min:200, max:5000, answer:3000, unit:"espèces", points:15 },
      { type:'mcq', q:"Que symbolise la loutre géante pour certains peuples indigènes d'Amazonie ?", answers:["Le gardien des rivières et des esprits de l'eau","Un esprit maléfique","Une simple source de nourriture","Un animal porte-bonheur sans signification particulière"], correct:0, points:10 },
    ]
  }
];

const SALOMON_COLLECTION = [
  { name:"Holographique", subtitle:"Édition limitée WWF", description:"Une paire aux reflets irisés évoquant la biodiversité des océans et forêts du monde entier.", emoji:"✨", tag:"HOLOGRAPHIQUE", tagColor:"#6B3FA0", style:"holographic" },
  { name:"Léopard de l'Amour", subtitle:"Édition limitée WWF", description:"Le motif léopard iconique, réinterprété en hommage à l'un des félins les plus rares de la planète.", emoji:"🐆", tag:"LÉOPARD", tagColor:"#7A4F2D", style:"leopard" }
];

const BASE_URL = window.location.origin + window.location.pathname.replace(/\/$/, '');
